import Navbar from '../../Navbar'
import React, { Fragment, useState, useEffect, useRef } from 'react'
import bgcolor from '../../../assets/bgcolor.png'
import Footer from '../../../components/Footer';
import { useTheme } from '../../../contexts/ThemeContext';
import { Link } from 'react-router-dom';

const CookiePolicy = () => {
    const { darkMode } = useTheme();

    const tranform3d = useRef();
    useEffect(() => {
        effect3d();
    }, []);

    const effect3d = () => {
        tranform3d.current.style.transform = `translate3d(0, 0, 0)`;
    };

    return (
        <Fragment>
            <Navbar darkMode={darkMode} />
            <div className={` ${darkMode && "dark "}`}>

                <div ref={tranform3d} className="dark:bg-dark overflow-hidden z-[-50] font-Manrope">
                    <img className="z-[-12] absolute" src={bgcolor} alt="" />

                    <div className='dark:text-white'>
                        <div className='flex flex-col justify-center items-center text-center mx-5 mt-10'>
                            <p className='py-3 text-5xl font-semibold'>Cookie Policy</p>
                            <p className='text-sm font-semibold'>Updated at 2024-03-01</p>
                        </div>
                        <div className='lg:px-32 md:px-20 px-7 py-10'>
                            <p className='text-2xl font-semibold'>Definitions and key terms</p>
                            <ul className='text-md flex flex-col gap-2 py-4 list-disc'>
                                <p>To help explain things as clearly as possible in this Cookie Policy, every time any of these terms are referenced, are strictly defined as:</p><br />
                                <li>
                                    Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
                                </li>
                                <li>
                                    Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to CoWin Pvt Ltd., Ottobrunn 85521, Germany that is responsible for your information under this Eula.
                                </li>
                                <li>Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
                                <li>
                                    Service: refers to the service provided by CoWin as described in the relative terms (if available) and on this platform.
                                </li>
                                <li>
                                    Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
                                </li>
                                <li>
                                    Website: site, which can be accessed via this URL: www.cowin.ai
                                </li>
                            </ul>
                            <p>This Disclaimer was created with <Link className='underline' to="/termify">Termify</Link></p>


                            <p className='text-2xl font-semibold pt-6'>Introduction</p>
                            <br />
                            <p className='text-md flex flex-col gap-2 py-4'>
                                This Cookie Policy explains how CoWin and its affiliates (collectively "CoWin", "we", "us", and "ours"), use cookies and similar technologies to recognize you when you visit our website/app, including without limitation www.cowin.ai and any related URLs, mobile or localized versions and related domains / sub-domains ("Websites"). It explains what these technologies are and why we use them, as well as the choices for how to control them.
                            </p>

                            <p className='text-2xl font-semibold pt-6'>What is a cookie?</p>
                            <p className='text-md py-4'>
                                A cookie is a small text file that is stored on your computer or other internet connected device in order to identify your browser, provide analytics, remember information about you such as your language preference or login information. They're completely safe and can't be used to run programs or deliver viruses to your device.
                            </p> <br />


                            <p className='text-2xl font-semibold'>Why do we use cookies?</p>
                            <ul className='text-md flex flex-col gap-2 py-4 list-disc'>
                                <p>We use first party and/or third party cookies on our website/app for various purposes such as:</p><br />
                                <li>
                                    To facilitate the operation and functionality of our website/app;
                                </li>
                                <li>
                                    To improve your experience of our website/app and make navigating around them quicker and easier;
                                </li>
                                <li>
                                    To allow us to make a bespoke user experience for you and for us to understand what is useful or of interest to you;
                                </li>
                                <li>To analyze how our website/app is used and how best we can customize it;</li>
                                <li>To identify future prospects and personalize marketing and sales interactions with it;</li>
                                <li>To facilitate the tailoring of online advertising to your interests.</li>
                                <li>You: a person or entity that is registered with CoWin to use the Services.</li>
                            </ul>


                            <img className="z-[-12] absolute" src={bgcolor} alt="" />
                            <p className='text-2xl font-semibold pt-6'>What type of cookies does CoWin use?</p>
                            <p className='text-md flex flex-col gap-2 py-4'>
                                Cookies can either be session cookies or persistent cookies. A session cookie expires automatically when you close your browser. A persistent cookie will remain until it expires or you delete your cookies. Expiration dates are set in the cookies themselves; some may expire after a few minutes while others may expire after multiple years. Cookies placed by the website you’re visiting are called “first party cookies”. <br /> <br />

                                Strictly Necessary cookies are necessary for our website/app to function and cannot be switched off in our systems. They are essential in order to enable you to navigate around the website/app and use its features. If you remove or disable these cookies, we cannot guarantee that you will be able to use our website/app. <br /> <br />

                                We use the following types of cookies in our website/app:
                            </p>


                            <p className='text-2xl font-semibold pt-6'>Essential Cookies</p>
                            <p className='text-md flex flex-col gap-2 py-4'>
                            We use essential cookies to make our website/app work. These cookies are strictly necessary to enable core functionality such as security, network management, your cookie preferences and accessibility. Without them you wouldn't be able to use basic services. You may disable these by changing your browser settings, but this may affect how the Websites function.
                            </p>

                            <p className='text-2xl font-semibold pt-6'>Performance and Functionality Cookies</p>
                            <p className='text-md flex flex-col gap-2 py-4'>
                            These cookies are used to enhance the performance and functionality of our website/app but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website/app as we would not be able to remember that you had logged in previously.
                            </p>

                            <p className='text-2xl font-semibold pt-6'>Social Media Cookies</p>
                            <p className='text-md flex flex-col gap-2 py-4'>
                            These cookies are used when you share information using a social media sharing button or “like” button on our Site or you link your account or engage with our content on or through a social networking website such as Facebook, Twitter or Google+. The social network will record that you have done this. These cookies may also include certain code that has been placed on the platform to help track conversions from ads, optimize ads based on collected data, build targeted audiences for future ads, and remarket to qualified users who have already taken certain action on the platform.
                            </p>

                            <p className='text-2xl font-semibold pt-6'>How you can manage cookies?</p>
                            <p className='text-md flex flex-col gap-2 py-4'>
                            Most browsers allow you to control cookies through their 'settings' preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall user experience, since it will no longer be personalized to you. It may also stop you from saving customized settings like login information. Browser manufacturers provide help pages relating to cookie management in their products.
                            </p>
                            <ul className='text-md flex flex-col gap-2 py-4 list-disc'>
                                <p>Browser manufacturers provide help pages relating to cookie management in their products. Please see below for more information.</p><br />
                                <li>Google Chrome</li>
                                <li>
                                Internet Explorer
                                </li>
                                <li>Mozilla Firefox</li>
                                <li>Safari (Desktop)</li>
                                <li>Safari (Mobile)</li>
                                <li>Android Browser</li>
                                <li>Opera</li>
                                <li>Opera Mobile</li>
                            </ul>

                            <p className='text-2xl font-semibold pt-6'>Blocking and disabling cookies and similar technologies</p>
                            <p className='text-md flex flex-col gap-2 py-4'>
                            Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser's help menu for more information.
                            </p>

                            <p className='text-2xl font-semibold pt-6'>Changes To Our Cookie Policy</p>
                            <p className='text-md py-4'>
                            We may change our Service and policies, and we may need to make changes to this Cookie Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Cookie Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Cookie Policy. If you do not want to agree to this or any updated Cookie Policy, you can delete your account.
                            </p>

                            <p className='text-2xl font-semibold pt-6'>Your Consent</p>
                            <p className='text-md py-4'>
                            By using our website/app, registering an account, or making a purchase, you hereby consent to our Cookie Policy and agree to its terms.
                            </p>

                            <p className='text-2xl font-semibold pt-6'>Contact Us</p>
                            <ul className='text-md flex flex-col gap-4 list-disc px-10'>
                                Don't hesitate to contact us if you have any questions
                                <li>
                                    Via Email: hi@cowin.ai
                                </li>
                                <li>
                                    Via this Link:
                                    <Link className='underline' to="/contactus">https://www.cowin.ai/contactus</Link>
                                </li>
                            </ul>

                        </div>

                    </div>
                    <Footer />
                </div>
            </div>
        </Fragment>
    )
}

export default CookiePolicy
