import Navbar from '../../Navbar'
import React, { Fragment, useState, useEffect, useRef } from 'react'
import bgcolor from '../../../assets/bgcolor.png'
import Footer from '../../../components/Footer';
import { useTheme } from '../../../contexts/ThemeContext';
import { Link } from 'react-router-dom';

const Disclaimer = () => {

    const { darkMode } = useTheme();

    const tranform3d = useRef();
    useEffect(() => {
        effect3d();
    }, []);

    const effect3d = () => {
        tranform3d.current.style.transform = `translate3d(0, 0, 0)`;
    };
    return (
        <Fragment>
            <Navbar darkMode={darkMode} />
            <div className={` ${darkMode && "dark "}`}>

                <div ref={tranform3d} className="dark:bg-dark overflow-hidden z-[-50] font-Manrope">
                    <img className="z-[-12] absolute" src={bgcolor} alt="" />

                    <div className='dark:text-white'>
                        <div className='flex flex-col justify-center items-center text-center mx-5 mt-10'>
                            <p className='py-3 text-5xl font-semibold'>Disclaimer</p>
                            <p className='text-sm font-semibold'>Updated at 2024-03-01</p>
                            <p className='lg:px-32 md:px-20 px-7 py-10 font-light'>
                                CoWin hereby grants you access to www.cowin.ai (“the Website”) and invites you to purchase the services offered here.
                            </p>
                        </div>
                        <div className='lg:px-32 md:px-20 px-7 py-10'>
                            <p className='text-2xl font-semibold'>Definitions and key terms</p>
                            <ul className='text-md flex flex-col gap-2 py-4 list-disc'>
                                <p>To help explain things as clearly as possible in this Eula, every time any of these terms are referenced, are strictly defined as:</p><br />
                                <li>
                                    Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
                                </li>
                                <li>
                                    Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to CoWin Pvt Ltd., Ottobrunn 85521, Germany that is responsible for your information under this Eula.
                                </li>
                                <li>
                                    Service: refers to the service provided by CoWin as described in the relative terms (if available) and on this platform.
                                </li>
                                <li>
                                    Website: site, which can be accessed via this URL: www.cowin.ai
                                </li>
                                <li>
                                    You: a person or entity that is registered with CoWin to use the Services.
                                </li>
                            </ul>
                            <p>This Disclaimer was created with <Link className='underline' to="/termify">Termify</Link></p> <br />

                            <p className='text-2xl font-semibold pt-6'>Limited liability</p>
                            <br />
                            <p className='text-md flex flex-col gap-2 py-4'>
                                CoWin endeavours to update and/or supplement the content of the website/app on a regular basis. Despite our care and attention, content may be incomplete and/or incorrect. <br /> <br />

                                The materials offered on the website/app are offered without any form of guarantee or claim to their correctness. These materials can be changed at any time without prior notice from CoWin. <br /> <br />

                                Particularly, all prices on the website/app are stated subject to typing and programming errors. No liability is assumed for the implications of such errors. No agreement is concluded on the basis of such errors. <br /> <br />

                                CoWin shall not bear any liability for hyperlinks to websites or services of third parties included on the website/app. From our website/app, you can visit other websites by following hyperlinks to such external sites. While we strive to provide only quality links to useful and ethical websites, we have no control over the content and nature of these sites. These links to other websites do not imply a recommendation for all the content found on these sites. Site owners and content may change without notice and may occur before we have the opportunity to remove a link which may have gone ‘bad’. <br /> <br />

                                Please be also aware that when you leave our website/app, other sites may have different privacy policies and terms which are beyond our control. Please be sure to check the Privacy Policies of these sites as well as their "Terms of Service" before engaging in any business or uploading any information. <br /> <br />
                            </p>

                            <p className='text-2xl font-semibold pt-6'>Errors and Omissions Disclaimer</p>
                            <p className='text-md py-4'>
                                CoWin is not responsible for any content, code or any other imprecision. <br /> <br />

                                CoWin does not provide warranties or guarantees. <br /> <br />

                                In no event shall CoWin be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. CoWin reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.
                            </p>

                            <p className='text-2xl font-semibold pt-6'>General Disclaimer</p>
                            <p className='text-md py-4'>
                                The CoWin Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. CoWin is a distributor and not a publisher of the content supplied by third parties; as such, CoWin exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the CoWin Service. Without limiting the foregoing, CoWin specifically disclaims all warranties and representations in any content transmitted on or in connection with the CoWin Service or on sites that may appear as links on the CoWin Service, or in the products provided as a part of, or otherwise in connection with, the CoWin Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by CoWin or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, CoWin does not warrant that the CoWin Service will be uninterrupted, uncorrupted, timely, or error-free.
                            </p>

                            <p className='text-2xl font-semibold pt-6'>Copyright Disclaimer</p>
                            <p className='text-md py-4'>
                                All intellectual property rights concerning these materials are vested in CoWin. Copying, distribution and any other use of these materials is not permitted without the written permission of CoWin, except and only to the extent otherwise provided in regulations of mandatory law (such as the right to quote), unless otherwise stated for certain materials.
                            </p>


                            <img className="z-[-12] absolute" src={bgcolor} alt="" />
                            <p className='text-2xl font-semibold pt-6'>Affiliate Links Disclosure</p>
                            <p className='text-md flex flex-col gap-2 py-4'>
                                CoWin has affiliate links and in this section of the Disclaimer we will address how we use those affiliate links from other websites/companies and products. These “affiliate links” are specific URLs that contain the affiliate's ID or username. <br /> <br />
                                In compliance with the FTC guidelines, please assume the following about links and posts on this site:
                            </p>
                            <ul className='text-md flex flex-col gap-2 py-4 list-disc'><li>
                                Any/all of the links on CoWin are affiliate links of which we receive a small commission from sales of certain items, but the price is the same for you. As CoWin has grown, so have costs associated with running and maintaining it, and affiliate links are a way we help offset these costs.
                            </li>
                                <li>
                                    If we post an affiliate link to a product, it is something that we personally use, support and would recommend without an affiliate link.
                                </li>
                                <li>
                                    Unless otherwise noted, all reviews are of items we have purchased and we are not paid or compensated in any way.
                                </li>
                            </ul>
                            <p className='text-md flex flex-col gap-2 py-4'>
                                We might participate in affiliate programs such as:
                            </p>
                            <ul className='text-md flex flex-col gap-2 py-4 list-disc'><li>Others</li>
                            </ul>


                            <p className='text-2xl font-semibold pt-6'>Educational Disclosure</p>
                            <p className='text-md flex flex-col gap-2 py-4'>
                                Any Information provided by CoWin is for educational purposes only, and is not to be interpreted as a recommendation for a specific treatment plan, product, or course of action. CoWin is a distributor and not a publisher of the content supplied by third parties; as such, CoWin exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information or educational content provided through or accessible via CoWin. Without limiting the foregoing, CoWin specifically disclaims all warranties and representations in any content transmitted on or in connection with CoWin or on sites that may appear as links on CoWin, or in the products provided as a part of, or otherwise in connection with, the CoWin. No oral advice or written information given by CoWin or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty.
                            </p>

                            <p className='text-2xl font-semibold pt-6'>Testimonials Disclosure</p>
                            <p className='text-md flex flex-col gap-2 py-4'>
                                Any testimonials provided on this platform are opinions of those providing them. The information provided in the testimonials is not to be relied upon to predict results in your specific situation. The results you experience will be dependent on many factors including but not limited to your level of personal responsibility, commitment, and abilities, in addition to those factors that you and/or CoWin may not be able to anticipate.  <br /> <br />

                                We will give honest testimonials to our visitors regardless of any discount. Any product or service that we test are individual experiences, reflecting real life experiences. The testimonials could be displayed on audio, text or video and are not necessarily representative of all of those who will use our products and/or services. <br /> <br />

                                CoWin does not guarantee the same results as the testimonials given on our platform. Testimonials presented on CoWin are applicable to the individuals writing them, and may not be indicative of future success of any other individuals. <br /> <br />

                                Please don’t hesitate to contact us if you would like to know more about testimonials, discounts, or any of the products/services that we review.
                            </p>

                            <p className='text-2xl font-semibold pt-6'>Your Consent</p>
                            <p className='text-md flex flex-col gap-2 py-4'>
                            We've updated our Disclaimer to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website/app, registering an account, or making a purchase, you hereby consent to our Disclaimer and agree to its terms.
                            </p>

                            <p className='text-2xl font-semibold pt-6'>Changes To Our Disclaimer</p>
                            <p className='text-md flex flex-col gap-2 py-4'>
                            Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies. Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to use the Service, you will be bound by the updated Disclaimer. If you do not want to agree to this or any updated Disclaimer, you can delete your account.
                            </p>

                           
                            <p className='text-2xl font-semibold pt-6'>Contact Us</p>
                            <ul className='text-md flex flex-col gap-4 list-disc px-10'>
                                Don't hesitate to contact us if you have any questions
                                <li>
                                    Via Email: hi@cowin.ai
                                </li>
                                <li>
                                    Via this Link:
                                    <Link className='underline' to="/contactus">https://www.cowin.ai/contactus</Link>
                                </li>
                            </ul>

                        </div>

                    </div>
                    <Footer />
                </div>
            </div>
        </Fragment>
    )
}

export default Disclaimer
