const Plan = [
  {
    id: 1,
    title: 'Features',
    offers: 'Credit',
    offers1: 'Interview CoPilot',
    offers2: 'Coding & Maths CoPilot',
    offers3: 'AI / LLM Models',
    offers4: 'Performance',
    offers5: 'Latency',
    offers6: 'Resume Generator',
    offers7: 'Cover-Letter Generator',
    offers8: 'Flashcard Interview',
    offers9: 'Mock Interview',
    offers10: '1:1 Mentorship',
    offers11: 'Mentee & Networking',
    offers12: 'Help & Support',
  },
  {
    id: 2,
    type: ' Test',
    type1: 'Drive',
    suggestion:'',
    currency: '$',
    fee: '0',
    duration: '/month',
    model: '1:1 "Mentorship"',
    title: 'KICK START FREE',
    offers: 'N/A',
    offers1: 'Free up to 5 mins',
    offers2: 'N/A',
    offers3: 'Basic',
    offers4: 'N/A',
    offers5: 'N/A',
    offers6: '1',
    offers7: '1',
    offers8: '1',
    offers9: 'Coming Soon !',
    offers10: 'Unlimited',
    offers11: 'Unlimited',
    offers12: 'Email',
  },
  {
    id: 3,
    type: 'Gear',
    type1: 'Up',
    suggestion:'',
    currency: '$',
    fee: '59',
    duration: '/month',
    model: '1 Round Kick-off',
    title: 'MONTHLY Billed',
    offers: '100 Credits Monthly',
    offers1: '(60mins) Monthly',
    offers2: '(60mins) Monthly',
    offers3: 'Advanced',
    offers4: '< 90%',
    offers5: '< 600ms',
    offers6: 'Unlimited',
    offers7: 'Unlimited',
    offers8: 'Unlimited',
    offers9: 'Coming Soon !',
    offers10: 'Unlimited',
    offers11: 'Unlimited',
    offers12: '24*7 Live Support',
    button: 'Start For FREE',
  },
  {
    id: 4,
    type: 'Take',
    type1: '-Off',
    suggestion:'Recommended',
    currency: '$',
    fee: '49',
    duration: '/month',
    model: '3-5 Rounds “Ace Interviews”',
    title: 'QUARTERLY Billed',
    offers: '300 Credits Quarterly',
    offers1: '(180 mins) Monthly',
    offers2: '(180 mins) Monthly',
    offers3: 'Advanced',
    offers4: '< 90%',
    offers5: '< 600ms',
    offers6: 'Unlimited',
    offers7: 'Unlimited',
    offers8: 'Unlimited',
    offers9: 'Coming Soon !',
    offers10: 'Unlimited',
    offers11: 'Unlimited',
    offers12: '24*7 Live Support',
    button: 'Start For FREE',
    button: 'Start For FREE',
  },
  {
    id: 5,
    type: 'God',
    type1: 'Mode',
    suggestion:'',
    currency: '$',
    fee: '39',
    duration: '/month',
    model: 'Year Long Companion',
    title: 'QUARTERLY Billed',
    offers: '1200 Credits Yearly',
    offers1: 'Unlimited Sessions',
    offers2: 'Unlimited Sessions',
    offers3: 'Advanced',
    offers4: '< 90%',
    offers5: '< 600ms',
    offers6: 'Unlimited',
    offers7: 'Unlimited',
    offers8: 'Unlimited',
    offers9: 'Coming Soon !',
    offers10: 'Unlimited',
    offers11: 'Unlimited',
    offers12: '24*7 Live Support',
    button: 'Start For FREE',
    button: 'Start For FREE',
    button: 'Start For FREE',
  }
];

export default Plan